/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Game: typeof import('./src/components/Game.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Screen: typeof import('./src/components/Screen.vue')['default']
  }
}
